### ISSUE TITLE
Does not support Maps

### ISSUE THREAD

**Issue by DynamiteAndy** [beenotung/compress-json#13]
Hi,

I am having issues using a map with this package,
I am using emoji.json (https://www.npmjs.com/package/emoji.json) and i am putting it into a map

```
  const mappedEmojis = emojiJson.reduce((accumulator, emoji: { char: string; name: string; group: string }) => {
    let category = accumulator.get(emoji.group);
    if (!category) {
      category = [];
      accumulator.set(emoji.group, category);
    }

    category.push(emoji);

    return accumulator;
  }, new Map());
  ```

This creates a map like this
![image](https://github.com/beenotung/compress-json/assets/152403382/d2b38b1b-4ed0-42c4-9b5b-c4c7fc6cf469)

This when compressed results in 
![image](https://github.com/beenotung/compress-json/assets/152403382/5fef86cf-8d56-4e5f-8ada-a5478d9f8daf)

Previously I was using an array

```
const mappedEmojis = emojiJson.map((emoji: { char: string; name: string; group: string }) => ({
    char: emoji.char,
    name: emoji.name,
    group: emoji.group
  }));
```

![image](https://github.com/beenotung/compress-json/assets/152403382/7e67838a-892d-4b51-95b4-9fdc79ea82da)

Which when compressed would give me this

![image](https://github.com/beenotung/compress-json/assets/152403382/72fa9e72-95a5-4ece-acb1-8e759ff91ee7)

Note the difference in sizes

EDIT: Also just to add thank you for this package! It more than halfed my userscript size :)

**Comment by beenotung** [comment]
This library only intends to directly support JSON values at the moment.

There are multiple workaround to convert the map into JSON-compatible values before `compress()`, and restore back to map after `decompress()`.

Sample data:

```javascript
let map = new Map()
map.set('a', 'apple')
map.set('b', 'banana')
map.set('c', 'cherry')
```

The compressed size is measured by:

```javascript
function size(data) {
  return JSON.stringify(compress(data)).length
}
```

**Option 1**: convert the map into array of entries

```javascript
let entries = Array.from(map)
let map2 = new Map(entries)
```

size(entries): 79

**Option 2**: convert the map into an object

```javascript
let dict = Object.fromEntries(Array.from(map))
let map2 = new Map(Object.entries(dict))
```

size(dict): 69

**Option 3**: convert the map into two arrays

```javascript
let keys = Array.from(map.keys())
let values = Array.from(map.values())

let map2 = new Map(keys.map((k, i) => [k, values[i]]))
```

size([keys,values]): 73

**Option 4**: convert the map into a single array

```javascript
let keys = Array.from(map.keys())
let values = Array.from(map.values())
let array = [...keys, ...values]

keys = array.slice(0, array.length / 2)
values = array.slice(array.length / 2)
let map2 = new Map(keys.map((k, i) => [k, values[i]]))
```

size(array): 61

The compression efficient of the last option should be the best because it is a flatten data layout, hence less encoding overhead.

**Comment by DynamiteAndy** [comment]
Thanks for this! :)
