### ISSUE TITLE
Cannot compress objects containing undefined values

### ISSUE THREAD

**Issue by ronkot** [beenotung/compress-json#7]
Thanks for great lib!

I just found out that `compress-json` throws an Error `TypeError: unsupported data type: [object Undefined]` if compressed object contains fields with `undefined` value.

Example:

```js
const data = [{a: 'b'}, {a: 'c', b: undefined}]
const compressed = compress(data)
```

I suppose it'd be possible to extend the lib to support also `undefined` values. Or, if it is not possible or works as defined, then a short notice to README would be great! ☀️

**Comment by beenotung** [comment]
This is intentional, json doesn't support undefined value. You may replace it with null for array element, or remove the property for object entry.

**Comment by beenotung** [comment]
If you really need to represent a key value pair with undefined value, you may need to escape when encoding, and unescape when decoding.

**Comment by beenotung** [comment]
Would you share about your use case?

**Comment by ronkot** [comment]
Okay, I see! Here's our use case in more detail:

Our code is run inside AWS lambda. Inside the logic we construct a very large payload (sometimes exceeding the 6MB Lambda payload limit). We use a shorthand to set some conditional fields to the response object:

```js
const payload = {
  optionalField: someCondition ? 'some-value' : undefined,
  //  ...
}
```

and stringify the payload in lambda handler response:

```js
return {
  statusCode: 200,
  body: JSON.stringify(payload)
}
```

As our payload may sometimes exceed the Lambda response 6MB size limit, I decided to compress it using `compress-json`, but the `undefined` values in payload caused the error as descibed in this issue.

Now I see that my initial issue description was a bit off. Actually we don't actually want to preserve the undefined fields, but to have similar behavior what `JSON.stringify()` does, ie. strip undefined values silently off. I fully agree that only standard JSON data types should be preserved in compression :)

I finally decided to just clean up the undefined values from payload using `JSON.parse(JSON.stringify(payload))` before passing it to `compress-json` and it works well.

So - after all there's no problem at all in your lib. I just incorrectly expected `JSON.stringify` like behavior. I'm closing this issue.

Thanks for your time for answering and developing this lib 🙏

**Comment by beenotung** [comment]
I see, your use case maybe not rare.

It may be handy to also silently skip undefined field when compressing for better efficiency 🤔

**Comment by beenotung** [comment]
I'd suggest another approach to handle undefined fields for better efficiency.

You can manually call helper function to delete undefined object fields. Doing that in application instead of internal encoding loop during compress will cause less performance overhead.

This is example, I'm calling `trimUndefined()` on ast object after creation to remove optional fields: https://github.com/beenotung/better-sql/blob/master/src/parse.ts#L376

In the current design of compress-json, it stores all object keys before the values. Therefore it will require additional scanning on all object entries to finalize the list of keys to be encoded. That is less efficient then calling `trimUndefined` only on objects with potential optional fields.

I may include the `trimUndefined` as helper function in this library in next release, and make it optionally recursive :)

**Comment by ronkot** [comment]
Ok, sounds feasible and nice to hear about  the internals 👍 Performance is not high priority in my use case but I understand well that in some other cases it's important. So it seems to be the traditional performance vs. usability trade-off 🙂

**Comment by papb** [comment]
Nice solution!

**Comment by beenotung** [comment]
I'm closing this issue for now, feel free to re-open it or submit another issue when new ideas comes up :)
